#!/usr/bin/env python3
"""Build data/airports.js: the nearby airports of each park.

Source: OurAirports (public domain), https://ourairports.com/data/
Only medium and large airports with scheduled passenger service and an IATA code.

For each park (the park point in index.html):
- the 3 nearest airports
- the nearest large airport, if it is not one of the 3 (it often has more flights)
Airports farther than 500 miles are left out, but each park keeps at least 2 airports.
The distance is the straight-line distance in miles.

Airports change very little, so the page does not refresh this file. Run the script again to update it:
    python3 scripts/build_airports.py                    # downloads airports.csv from OurAirports
    python3 scripts/build_airports.py airports.json      # or a local OurAirports JSON or CSV file
"""
import csv
import datetime as dt
import io
import json
import math
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fetch_history as fh  # noqa: E402  (load_parks)

ROOT = fh.ROOT
OUT = ROOT / "data" / "airports.js"
CSV_URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"
COUNTRIES = {"US", "PR", "VI", "AS", "GU", "MP"}  # the United States and its territories
NEAREST = 3
MAX_MILES = 500        # leave out airports farther than this ...
MIN_AIRPORTS = 2       # ... but always keep at least this many


def load_airports(src):
    if src:
        text = Path(src).read_text(encoding="utf-8")
        rows = json.loads(text) if src.endswith(".json") else list(csv.DictReader(io.StringIO(text)))
    else:
        with urllib.request.urlopen(CSV_URL, timeout=60) as r:
            rows = list(csv.DictReader(io.StringIO(r.read().decode("utf-8"))))
    out = []
    for a in rows:
        if (a.get("iso_country") in COUNTRIES and a.get("type") in ("large_airport", "medium_airport")
                and str(a.get("scheduled_service")).lower() in ("yes", "true") and (a.get("iata_code") or "").strip()):
            out.append({"iata": a["iata_code"].strip(), "name": a["name"].strip(), "city": (a.get("municipality") or "").strip(),
                        "large": a["type"] == "large_airport", "lat": float(a["latitude_deg"]), "lon": float(a["longitude_deg"])})
    return out


def miles(lat1, lon1, lat2, lon2):
    r = math.radians
    a = math.sin(r(lat2 - lat1) / 2) ** 2 + math.cos(r(lat1)) * math.cos(r(lat2)) * math.sin(r(lon2 - lon1) / 2) ** 2
    return 3958.8 * 2 * math.asin(math.sqrt(a))


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else None
    airports = load_airports(src)
    print(len(airports), "airports with scheduled service")
    parks = fh.load_parks()
    out = {}
    for p in parks:
        dist = lambda a: miles(p["lat"], p["lon"], a["lat"], a["lon"])
        ranked = sorted(airports, key=dist)
        pick = [a for a in ranked[:NEAREST] if dist(a) <= MAX_MILES] or []
        pick = pick if len(pick) >= MIN_AIRPORTS else ranked[:MIN_AIRPORTS]
        if not any(a["large"] for a in pick):
            big = next((a for a in ranked if a["large"]), None)
            if big and dist(big) <= MAX_MILES:
                pick.append(big)
        out[p["id"]] = [{"iata": a["iata"], "name": a["name"], "city": a["city"], "large": a["large"],
                         "mi": round(miles(p["lat"], p["lon"], a["lat"], a["lon"]))} for a in pick]
    data = {"source": "OurAirports (public domain), medium and large airports with scheduled service",
            "built": dt.date.today().isoformat(), "parks": out}
    OUT.write_text("// Generated by scripts/build_airports.py. Do not edit by hand.\n"
                   "// mi = straight-line distance in miles from the park point. large = a large airport.\n"
                   "window.PARK_AIRPORTS = " + json.dumps(data, separators=(",", ":"), ensure_ascii=False) + ";\n", encoding="utf-8")
    print("wrote", OUT, OUT.stat().st_size, "bytes")


if __name__ == "__main__":
    main()
