#!/usr/bin/env python3
"""Keep data/park-history.js: monthly visits and monthly weather for each park.

Visits:  NPS Visitor Use Statistics (irmaservices.nps.gov), recreation visits per month.
Weather: Open-Meteo historical archive (archive-api.open-meteo.com). For each month:
         the mean of the daily high, the mean of the daily low, the total rain and the total snow.

The file stores every month from FIRST_MONTH to the last month with data. Old months do not
change, so the script only adds new months:

1. A month is a candidate only after it ends (October is a candidate from November 1).
2. The script gets the candidate month for the first park only.
   If the visits or the weather of the first park are not available yet, the script stops.
   It does not request data for the other parks, and the file does not change.
3. If the first park has data, the script gets that month for all parks and adds it.

The park list (id, code, lat, lon) comes from index.html. Standard library only.
Run: python3 scripts/fetch_history.py
"""
import calendar
import datetime as dt
import json
import re
import socket
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "park-history.js"
FIRST_MONTH = "2023-01"     # the first month in the file
SOCKET_TIMEOUT = 20         # seconds for each network step: connect, TLS handshake, each read
TRIES = 3                   # tries for each request
SCRIPT_DEADLINE = 12 * 60   # seconds for the whole script
MAX_FAILS_IN_A_ROW = 3      # stop using a host after this many parks fail one after the other
# NPS Visitor Use Statistics reports Sequoia and Kings Canyon as separate units.
STATS_CODE = {"seki": "SEQU", "kica": "KICA"}
START = time.monotonic()


class DeadlineExceeded(Exception):
    pass


def time_left():
    left = SCRIPT_DEADLINE - (time.monotonic() - START)
    if left <= 0:
        raise DeadlineExceeded(f"script deadline of {SCRIPT_DEADLINE} s reached")
    return left


def get_json(url):
    """GET a JSON document with a socket timeout and a limited number of tries."""
    print("GET", url, flush=True)
    last = None
    for i in range(TRIES):
        t0 = time.monotonic()
        try:
            req = urllib.request.Request(url, headers={"Accept": "application/json", "User-Agent": "National-Park-Status data script"})
            # The timeout applies to each socket operation: connect, TLS handshake and each read.
            with urllib.request.urlopen(req, timeout=min(SOCKET_TIMEOUT, time_left())) as r:
                body = r.read()
            print(f"  {len(body)} bytes in {time.monotonic() - t0:.1f} s", flush=True)
            return json.loads(body.decode("utf-8"))
        except DeadlineExceeded:
            raise
        except (urllib.error.URLError, socket.timeout, TimeoutError, ConnectionError, ValueError) as e:
            last = e
            print(f"  try {i + 1} of {TRIES} failed after {time.monotonic() - t0:.1f} s: {e}", flush=True)
            if i < TRIES - 1:
                time.sleep(min(2 * 2 ** i, time_left()))
    raise RuntimeError(f"{url} failed {TRIES} times: {last}")


# ---- months ----
def ym(s):
    return int(s[:4]), int(s[5:7])


def ym_str(y, m):
    return f"{y:04d}-{m:02d}"


def add_months(s, n):
    y, m = ym(s)
    k = y * 12 + (m - 1) + n
    return ym_str(k // 12, k % 12 + 1)


def months_between(a, b):
    """Number of months from a to b (b - a)."""
    (ya, ma), (yb, mb) = ym(a), ym(b)
    return (yb - ya) * 12 + (mb - ma)


def last_complete_month(today):
    return add_months(ym_str(today.year, today.month), -1)


# ---- inputs ----
def load_parks():
    html = (ROOT / "index.html").read_text(encoding="utf-8")
    parks = []
    for m in re.finditer(r'\{r:(\d+), code:"(\w+)",(?: id:"(\w+)",)? name:"([^"]+)".*?lat:(-?[\d.]+), lon:(-?[\d.]+)', html):
        r, code, pid, name, lat, lon = m.groups()
        parks.append({"id": pid or code, "code": code, "name": name, "lat": float(lat), "lon": float(lon)})
    if len(parks) != 63:
        sys.exit(f"Expected 63 parks in index.html, found {len(parks)}")
    return parks


def load_store():
    """Read the data file. Returns None if there is no file or the file has an old format."""
    if not OUT.exists():
        return None
    m = re.search(r"window\.PARK_HISTORY = (\{.*\});", OUT.read_text(encoding="utf-8"), re.S)
    data = json.loads(m.group(1)) if m else None
    if not data or data.get("format") != 2:
        return None
    return data


def save_store(data):
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("// Generated by scripts/fetch_history.py. Do not edit by hand.\n"
                   "// Each array has one value for each month from \"first\" to \"last\".\n"
                   "window.PARK_HISTORY = " + json.dumps(data, separators=(",", ":"), ensure_ascii=False) + ";\n",
                   encoding="utf-8")
    print("wrote", OUT, OUT.stat().st_size, "bytes", flush=True)


# ---- sources ----
def stats_code(p):
    return STATS_CODE.get(p["id"], p["id"].upper())


def records(payload):
    if isinstance(payload, list):
        return payload
    if isinstance(payload, dict):
        for v in payload.values():
            if isinstance(v, list) and v and isinstance(v[0], dict):
                return v
    return []


def fetch_visits(codes, start, end):
    """Returns {UNITCODE: {"YYYY-MM": visits or None}} for the months from start to end."""
    (ys, ms), (ye, me) = ym(start), ym(end)
    out = {}
    for i in range(0, len(codes), 20):
        batch = codes[i:i + 20]
        q = urllib.parse.urlencode({"unitCodes": ",".join(batch), "startMonth": ms, "startYear": ys,
                                    "endMonth": me, "endYear": ye})
        for rec in records(get_json("https://irmaservices.nps.gov/v3/rest/stats/visitation?" + q)):
            if not {"UnitCode", "Year", "Month", "RecreationVisitors"} <= rec.keys():
                raise RuntimeError(f"Visitor statistics: unknown fields {list(rec)}")
            v = rec["RecreationVisitors"]
            out.setdefault(rec["UnitCode"].upper(), {})[ym_str(int(rec["Year"]), int(rec["Month"]))] = None if v is None else int(v)
        time.sleep(1)
    return out


def fetch_weather(p, start, end):
    """Returns {"YYYY-MM": {"hi", "lo", "rain", "snow"} or None}. None means a month with missing days."""
    last_day = calendar.monthrange(*ym(end))[1]
    q = urllib.parse.urlencode({
        "latitude": p["lat"], "longitude": p["lon"],
        "start_date": f"{start}-01", "end_date": f"{end}-{last_day:02d}",
        "daily": "temperature_2m_max,temperature_2m_min,rain_sum,snowfall_sum",
        "temperature_unit": "fahrenheit", "precipitation_unit": "inch", "timezone": "auto"})
    d = get_json("https://archive-api.open-meteo.com/v1/archive?" + q).get("daily") or {}
    days = {}
    for t, mx, mn, r, s in zip(d.get("time", []), d.get("temperature_2m_max", []), d.get("temperature_2m_min", []),
                               d.get("rain_sum", []), d.get("snowfall_sum", [])):
        days.setdefault(t[:7], []).append((mx, mn, r, s))
    out = {}
    n = months_between(start, end) + 1
    for k in range(n):
        mon = add_months(start, k)
        rows = days.get(mon, [])
        complete = len(rows) == calendar.monthrange(*ym(mon))[1] and all(None not in row for row in rows)
        if not complete:
            out[mon] = None
            continue
        out[mon] = {"hi": round(sum(r[0] for r in rows) / len(rows), 1),
                    "lo": round(sum(r[1] for r in rows) / len(rows), 1),
                    "rain": round(sum(r[2] for r in rows), 2),
                    "snow": round(sum(r[3] for r in rows), 1)}
    return out


# ---- main ----
def main():
    today = dt.date.today()
    parks = load_parks()
    store = load_store()
    target = last_complete_month(today)  # the newest month that has ended

    if store is None:
        print(f"No data file in the current format. Getting all months from {FIRST_MONTH}.", flush=True)
        start = FIRST_MONTH
    else:
        start = add_months(store["last"], 1)
    if months_between(start, target) < 0:
        print(f"The file has data to {store['last']}. The next month, {start}, has not ended. Nothing to do.")
        return

    # Step 1: the first park only. Find the newest month that has visits and complete weather.
    first = parks[0]
    print(f"Checking {start} to {target} for the first park, {first['name']}.", flush=True)
    v1 = fetch_visits([stats_code(first)], start, target).get(stats_code(first), {})
    w1 = fetch_weather(first, start, target)
    end = None
    for k in range(months_between(start, target) + 1):
        mon = add_months(start, k)
        if v1.get(mon) is None or w1.get(mon) is None:
            print(f"The first park has no {'visits' if v1.get(mon) is None else 'complete weather'} for {mon}. "
                  f"The script stops here and does not request data for the other parks.", flush=True)
            break
        end = mon
    if end is None:
        print("No new data. The data file did not change.")
        return
    print(f"New months: {start} to {end}. Getting them for all parks.", flush=True)

    # Step 2: all parks, new months only.
    codes = sorted({stats_code(p) for p in parks})
    visits = fetch_visits(codes, start, end)
    weather, errors, fails_in_a_row = {}, [], 0
    for p in parks:
        if p is first:
            weather[p["id"]] = w1
            continue
        print("weather", p["id"], p["name"], flush=True)
        try:
            weather[p["id"]] = fetch_weather(p, start, end)
            fails_in_a_row = 0
        except DeadlineExceeded as e:
            errors.append(f"weather: {e}")
            break
        except Exception as e:
            errors.append(f"weather {p['id']}: {e}")
            print(f"ERROR weather {p['id']}:", e, flush=True)
            fails_in_a_row += 1
            if fails_in_a_row >= MAX_FAILS_IN_A_ROW:
                errors.append(f"weather: stopped after {fails_in_a_row} parks failed one after the other")
                break
        time.sleep(0.5)
    if errors:
        # Do not add months with holes. The next run tries the same months again.
        sys.exit("Weather failed. The data file did not change.\n" + "\n".join(errors[:20]))

    # Step 3: add the new months.
    new_months = [add_months(start, k) for k in range(months_between(start, end) + 1)]
    if store is None:
        store = {"format": 2, "first": FIRST_MONTH, "last": None, "parks": {}}
    for p in parks:
        rec = store["parks"].setdefault(p["id"], {"v": [], "hi": [], "lo": [], "rain": [], "snow": []})
        pv = visits.get(stats_code(p), {})
        for mon in new_months:
            w = weather[p["id"]].get(mon) or {}
            rec["v"].append(pv.get(mon))
            for key in ("hi", "lo", "rain", "snow"):
                rec[key].append(w.get(key))
    store["last"] = end
    store["updated"] = today.isoformat()
    store["sources"] = {"visits": "NPS Visitor Use Statistics, recreation visits",
                        "weather": "Open-Meteo historical weather archive (ERA5)"}
    save_store(store)


if __name__ == "__main__":
    main()
