#!/usr/bin/env python3
"""Keep the fall foliage data for each park. Two parts, two files:

1. data/foliage.js: typical timing from satellite (NASA MODIS land surface phenology, MCD12Q2,
   from the ORNL DAAC MODIS web service). For each park and year: the day greenness starts to
   drop (Senescence), the middle of the leaf change (MidGreendown) and leaves off (Dormancy).
   Each value is the median of the pixels in a 3 km x 3 km box at the park point.
   NASA publishes one year at a time, 1 to 2 years late. Old years do not change, so the script
   only adds new years. It first checks the first park. If the first park has no data for the
   new year, it stops and does not request data for the other parks.

2. data/foliage-now.js: this season, from the USA National Phenology Network (USA-NPN).
   Reports of "Colored leaves" and "Falling leaves" within 50 km of each park in the last 14 days.
   One request covers all parks. The script refreshes this part only from Aug 15 to Dec 15.

The park list comes from index.html. HTTP helpers and timeouts come from fetch_history.py.
Run: python3 scripts/fetch_foliage.py [--typical] [--now]   (default: both)
"""
import datetime as dt
import json
import math
import re
import statistics
import sys
import time
import urllib.parse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fetch_history as fh  # noqa: E402  (get_json with timeouts, load_parks)

fh.SCRIPT_DEADLINE = 20 * 60  # the satellite backfill makes about 250 requests
ROOT = fh.ROOT
TYPICAL_OUT = ROOT / "data" / "foliage.js"
NOW_OUT = ROOT / "data" / "foliage-now.js"

MODIS = "https://modis.ornl.gov/rst/api/v1/"
PRODUCT = "MCD12Q2"
FIRST_YEAR = 2019            # keep this many recent years: the page averages the last 5
BANDS = {"sen": r"Senescence\.Num_Modes_01", "mid": r"MidGreendown\.Num_Modes_01",
         "dor": r"Dormancy\.Num_Modes_01", "amp": r"EVI_Amplitude\.Num_Modes_01"}
FILL = 32767
KM = 1                       # 1 km above, below, left and right: a 3 x 3 km box (500 m pixels)

NPN = "https://services.usanpn.org/npn_portal/"
SEASON = ((8, 15), (12, 15)) # month, day: the period when the script gets this-season reports
NOW_DAYS = 14
NEAR_KM = 50


# ---------- shared ----------
def write_js(path, var, data, note):
    path.parent.mkdir(exist_ok=True)
    path.write_text(f"// Generated by scripts/fetch_foliage.py. Do not edit by hand.\n// {note}\n"
                    f"window.{var} = " + json.dumps(data, separators=(",", ":"), ensure_ascii=False) + ";\n",
                    encoding="utf-8")
    print("wrote", path, path.stat().st_size, "bytes", flush=True)


def read_js(path, var):
    if not path.exists():
        return None
    m = re.search(r"window\." + var + r" = (\{.*\});", path.read_text(encoding="utf-8"), re.S)
    return json.loads(m.group(1)) if m else None


# ---------- part 1: typical timing (MODIS) ----------
def modis_get(path, **params):
    return fh.get_json(MODIS + path + "?" + urllib.parse.urlencode(params))


def band_names():
    data = modis_get(f"{PRODUCT}/bands")
    names = [b.get("band") for b in data.get("bands", [])]
    out = {}
    for key, pat in BANDS.items():
        match = [n for n in names if n and re.fullmatch(pat, n)]
        if not match:
            raise RuntimeError(f"MODIS: no band for {pat}. Bands: {names}")
        out[key] = match[0]
    return out


def available_years(p):
    data = modis_get(f"{PRODUCT}/dates", latitude=p["lat"], longitude=p["lon"])
    return sorted({int(d["calendar_date"][:4]) for d in data.get("dates", [])})


def park_years(p, bands, years):
    """Returns {year: {"sen","mid","dor" (day of year) and "amp", or None}} for the years given."""
    raw = {y: {} for y in years}
    for key, band in bands.items():
        # The service allows at most 10 dates in one request.
        for i in range(0, len(years), 10):
            ys = years[i:i + 10]
            data = modis_get(f"{PRODUCT}/subset", latitude=p["lat"], longitude=p["lon"], band=band,
                             startDate=f"A{ys[0]}001", endDate=f"A{ys[-1]}365",
                             kmAboveBelow=KM, kmLeftRight=KM)
            try:
                scale = float(data.get("scale") or 1) or 1
            except (TypeError, ValueError):  # for example "Not applicable" for the date bands
                scale = 1
            for s in data.get("subset", []):
                y = int(s["calendar_date"][:4])
                if y in raw:
                    raw[y][key] = [v for v in s.get("data", []) if v is not None and v != FILL and v >= 0], scale
    out = {}
    for y in years:
        r = raw[y]
        if not all(k in r for k in BANDS) or not r["mid"][0]:
            out[y] = None  # the year is not available, or no pixel has a growing cycle
            continue
        jan1 = (dt.date(y, 1, 1) - dt.date(1970, 1, 1)).days
        # Values are days since 1970-01-01. Keep only dates in this growing year.
        dates = {k: [v for v in r[k][0] if jan1 <= v <= jan1 + 430] for k in ("sen", "mid", "dor")}
        if not dates["mid"]:
            out[y] = None
            continue
        rec = {"n": len(dates["mid"])}
        for k in ("sen", "mid", "dor"):
            vals = dates[k]
            # Values are days since 1970-01-01. Store the day of the year (Jan 1 = 0).
            rec[k] = round(statistics.median(vals) - jan1) if vals else None
        amp, scale = r["amp"]
        rec["amp"] = round(statistics.median(amp) * scale, 3) if amp else None
        out[y] = rec
    return out


def update_typical(parks):
    store = read_js(TYPICAL_OUT, "PARK_FOLIAGE")
    if not store or store.get("format") != 1:
        store = None
    first = parks[0]
    have = set(map(int, store["years"])) if store else set()
    avail = [y for y in available_years(first) if y >= FIRST_YEAR]
    new = [y for y in avail if y not in have]
    if not new:
        print(f"Typical timing: no new year. The newest year in the file is {max(have) if have else 'none'}.")
        return False
    print(f"Typical timing: the service lists {avail}. New years: {new}.", flush=True)
    bands = band_names()
    print("bands:", bands, flush=True)

    # Step 1: the first park only. Keep the new years that have data.
    r1 = park_years(first, bands, new)
    new = [y for y in new if r1.get(y)]
    if not new:
        print("The first park has no data for the new years. The script stops here "
              "and does not request data for the other parks.")
        return False

    # Step 2: all parks, new years only. A park that fails (after 3 tries for each request)
    # stops the update, so the file never has holes. The next run tries the same years again.
    results = {first["id"]: r1}
    for p in parks[1:]:
        print("foliage", p["id"], p["name"], flush=True)
        results[p["id"]] = park_years(p, bands, new)
    if store is None:
        store = {"format": 1, "years": [], "parks": {}}
    for p in parks:
        rec = store["parks"].setdefault(p["id"], {})
        for y in new:
            rec[str(y)] = results[p["id"]].get(y)
    store["years"] = sorted(set(store["years"]) | set(new))
    store["updated"] = dt.date.today().isoformat()
    store["source"] = "NASA MODIS land surface phenology (MCD12Q2), ORNL DAAC MODIS web service"
    write_js(TYPICAL_OUT, "PARK_FOLIAGE", store,
             "Day of the year (Jan 1 = 0) when greenness starts to drop (sen), the middle of the change (mid) and leaves off (dor).")
    return True


# ---------- part 2: this season (USA-NPN) ----------
def in_season(d):
    (m1, d1), (m2, d2) = SEASON
    return dt.date(d.year, m1, d1) <= d <= dt.date(d.year, m2, d2)


def km(lat1, lon1, lat2, lon2):
    r = math.radians
    a = math.sin(r(lat2 - lat1) / 2) ** 2 + math.cos(r(lat1)) * math.cos(r(lat2)) * math.sin(r(lon2 - lon1) / 2) ** 2
    return 6371 * 2 * math.asin(math.sqrt(a))


def phenophase_ids():
    data = fh.get_json(NPN + "phenophases/getPhenophases.json")
    rows = data if isinstance(data, list) else data.get("phenophases", [])
    ids = {"colored": [], "falling": []}
    for row in rows:
        name = (row.get("phenophase_name") or "").strip().lower()
        if name == "colored leaves":
            ids["colored"].append(int(row["phenophase_id"]))
        elif name == "falling leaves":
            ids["falling"].append(int(row["phenophase_id"]))
    if not ids["colored"]:
        raise RuntimeError("USA-NPN: no phenophase named 'Colored leaves'")
    return ids


def update_now(parks, today):
    if not in_season(today):
        print(f"This season: {today} is outside Aug 15 to Dec 15. No request.")
        return False
    ids = phenophase_ids()
    print("phenophase ids:", ids, flush=True)
    start = today - dt.timedelta(days=NOW_DAYS)
    # Do not send a bounding box: with the box parameters, the service returns no reports (tested Oct 2026).
    # The script finds the reports near each park by distance.
    params = [("request_src", "national-park-status"), ("start_date", start.isoformat()), ("end_date", today.isoformat())]
    for i, pid in enumerate(ids["colored"] + ids["falling"]):
        params.append((f"phenophase_id[{i}]", pid))
    data = fh.get_json(NPN + "observations/getObservations.json?" + urllib.parse.urlencode(params))
    rows = data if isinstance(data, list) else data.get("observations", [])
    print(f"{len(rows)} reports. Fields: {sorted(rows[0]) if rows else 'none'}", flush=True)
    if not rows:
        # Check the request: the same dates one year earlier. Observers often enter reports some weeks late.
        old = [(k, v.replace(str(today.year), str(today.year - 1)) if k in ("start_date", "end_date") else v) for k, v in params]
        prev = fh.get_json(NPN + "observations/getObservations.json?" + urllib.parse.urlencode(old))
        prev = prev if isinstance(prev, list) else prev.get("observations", [])
        print(f"Check: the same dates one year earlier have {len(prev)} reports. "
              + ("The request works. The reports for this period are not entered yet." if prev else "The request may be wrong."), flush=True)
    kind = {pid: "colored" for pid in ids["colored"]} | {pid: "falling" for pid in ids["falling"]}
    out = {}
    for p in parks:
        rec = {"colored": [0, 0], "falling": [0, 0], "sites": set(), "last": None}
        for o in rows:
            try:
                lat, lon, pid, status = float(o["latitude"]), float(o["longitude"]), int(o["phenophase_id"]), int(o["phenophase_status"])
            except (KeyError, TypeError, ValueError):
                continue
            if status not in (0, 1) or pid not in kind or km(p["lat"], p["lon"], lat, lon) > NEAR_KM:
                continue
            k = kind[pid]
            rec[k][1] += 1
            rec[k][0] += status
            rec["sites"].add(o.get("site_id"))
            d = o.get("observation_date")
            if d and (rec["last"] is None or d > rec["last"]):
                rec["last"] = d
        if rec["colored"][1] or rec["falling"][1]:
            out[p["id"]] = {"colored": rec["colored"], "falling": rec["falling"], "sites": len(rec["sites"]), "last": rec["last"]}
    write_js(NOW_OUT, "PARK_FOLIAGE_NOW",
             {"from": start.isoformat(), "to": today.isoformat(), "km": NEAR_KM, "parks": out,
              "source": "USA National Phenology Network (usanpn.org)"},
             "[yes, reports] for 'Colored leaves' and 'Falling leaves' within 'km' of each park.")
    return True


def main():
    args = set(sys.argv[1:]) or {"--typical", "--now"}
    parks = fh.load_parks()
    errors = []
    if "--typical" in args:
        try:
            update_typical(parks)
        except Exception as e:
            errors.append(f"typical timing: {e}")
            print("ERROR typical timing:", e, flush=True)
    if "--now" in args:
        try:
            update_now(parks, dt.date.today())
        except Exception as e:
            errors.append(f"this season: {e}")
            print("ERROR this season:", e, flush=True)
    if errors:
        sys.exit("\n".join(errors))


if __name__ == "__main__":
    main()
